/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
// Hand-written integration tests for com.microsoft contrib operators.
// Unlike tests/onnx_ops/, this file is NOT regenerated by
// scripts/generate_rust_op_conversion_tests.py.

// The shared runner also exposes expectation variants only the generated
// suite constructs.
#[allow(dead_code)]
mod common;

use common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::{ModelProto, OperatorSetIdProto, TensorProto};

fn with_ms_domain(mut model: ModelProto, ms_version: i64) -> ModelProto {
    model.opset_import.push(OperatorSetIdProto {
        domain: "com.microsoft".to_string(),
        version: ms_version,
    });
    model
}

/// MatMulBnb4 with the NF4 codebook: A[2,16] x dequant(B)[16,4].
/// The runner dispatches the converted WebNN graph and compares against ORT,
/// which validates the codebook values and the high/low nibble packing order.
fn build_matmul_bnb4(quant_type: i64) -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    let (k, n, block_size) = (16i64, 4i64, 16i64);
    let total = (k * n) as usize;
    // All 16 codes appear, exercising the whole codebook.
    let packed: Vec<u8> = (0..total / 2)
        .map(|i| ((i % 16) as u8) << 4 | ((15 - i % 16) as u8))
        .collect();
    let absmax: Vec<f32> = vec![0.5, 1.25, 2.0, 0.75];

    let mut node = node(
        "MatMulBnb4",
        "test_matmul_bnb4",
        &["A", "B", "absmax"],
        &["Y"],
        &[
            attr_int("K", k),
            attr_int("N", n),
            attr_int("block_size", block_size),
            attr_int("quant_type", quant_type),
        ],
    );
    node.domain = "com.microsoft".to_string();

    let model = model(
        17,
        graph(
            "test_MatMulBnb4_graph",
            vec![f32_input("A", &[2, k])],
            vec![f32_output("Y", &[2, n])],
            vec![node],
            vec![
                u8_init("B", &[(total / 2) as i64], &packed),
                f32_init("absmax", &[(total as i64) / block_size], &absmax),
            ],
        ),
    );
    with_ms_domain(model, 1)
}

/// GroupQueryAttention with grouped KV heads (H=2, kvH=1) and a non-empty
/// KV cache (P=2, S=4). `seqlens_k`/`total_sequence_length` are constant
/// initializers set to the unpadded values the static lowering assumes, so
/// ORT computes the same attention pattern the WebNN causal mask encodes.
fn build_gqa() -> ModelProto {
    build_gqa_with(false, None)
}

/// `packed`: query carries Q, K and V ([B, S, (H + 2*kvH)*Dh]) and the key/value
/// inputs are empty. `rotary`: do_rotary=1 with cos/sin caches
/// ([max_seq, Dh/2]) and the given `rotary_interleaved` flag.
fn build_gqa_with(packed: bool, rotary: Option<bool>) -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    // ORT's rotary path requires head_size % 16 == 0.
    let (num_heads, kv_heads, head_dim) = (2i64, 1i64, 16i64);
    let (seq, past_seq) = (4i64, 2i64);
    let total_seq = seq + past_seq;
    let max_seq = 8i64;

    let mut input_names = vec![
        "query",
        if packed { "" } else { "key" },
        if packed { "" } else { "value" },
        "past_key",
        "past_value",
        "seqlens_k",
        "total_seq_len",
    ];
    let mut attrs = vec![
        attr_int("num_heads", num_heads),
        attr_int("kv_num_heads", kv_heads),
    ];
    if let Some(interleaved) = rotary {
        input_names.extend(["cos_cache", "sin_cache"]);
        attrs.push(attr_int("do_rotary", 1));
        attrs.push(attr_int("rotary_interleaved", i64::from(interleaved)));
    }
    let mut gqa = node(
        "GroupQueryAttention",
        "test_gqa",
        &input_names,
        &["Y", "present_key", "present_value"],
        &attrs,
    );
    gqa.domain = "com.microsoft".to_string();

    let query_hidden = if packed {
        (num_heads + 2 * kv_heads) * head_dim
    } else {
        num_heads * head_dim
    };
    let mut inputs = vec![f32_input("query", &[1, seq, query_hidden])];
    if !packed {
        inputs.push(f32_input("key", &[1, seq, kv_heads * head_dim]));
        inputs.push(f32_input("value", &[1, seq, kv_heads * head_dim]));
    }
    inputs.push(f32_input("past_key", &[1, kv_heads, past_seq, head_dim]));
    inputs.push(f32_input("past_value", &[1, kv_heads, past_seq, head_dim]));

    let mut initializers = vec![
        i32_init("seqlens_k", &[1], &[(total_seq - 1) as i32]),
        i32_init("total_seq_len", &[1], &[total_seq as i32]),
    ];
    if rotary.is_some() {
        let half = head_dim / 2;
        let table = |seed: i64| -> Vec<f32> {
            (0..max_seq * half)
                .map(|i| (((i * 13 + seed * 7) % 21) as f32 / 10.0) - 1.0)
                .collect()
        };
        initializers.push(f32_init("cos_cache", &[max_seq, half], &table(1)));
        initializers.push(f32_init("sin_cache", &[max_seq, half], &table(2)));
    }

    let model = model(
        17,
        graph(
            "test_GroupQueryAttention_graph",
            inputs,
            vec![
                f32_output("Y", &[1, seq, num_heads * head_dim]),
                f32_output("present_key", &[1, kv_heads, total_seq, head_dim]),
                f32_output("present_value", &[1, kv_heads, total_seq, head_dim]),
            ],
            vec![gqa],
            initializers,
        ),
    );
    with_ms_domain(model, 1)
}

/// GatherBlockQuantized over an INT4 (data type 22) table: logical dims,
/// two's-complement nibbles, no zero points (defaults to 0 for signed types).
fn build_gather_block_quantized_int4() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    let (rows, cols, block_size) = (8i64, 32i64, 16i64);
    let blocks = cols / block_size;
    let packed: Vec<u8> = (0..rows * cols / 2)
        .map(|i| ((i * 5 + 3) % 256) as u8)
        .collect();
    let scales: Vec<f32> = (0..rows * blocks)
        .map(|i| 0.02 + (i % 7) as f32 * 0.01)
        .collect();
    let data = TensorProto {
        name: "data".to_string(),
        data_type: 22, // INT4
        dims: vec![rows, cols],
        raw_data: packed,
        ..Default::default()
    };

    let mut gbq = node(
        "GatherBlockQuantized",
        "test_gbq_int4",
        &["data", "indices", "scales"],
        &["Y"],
        &[
            attr_int("block_size", block_size),
            attr_int("gather_axis", 0),
            attr_int("quantize_axis", 1),
        ],
    );
    gbq.domain = "com.microsoft".to_string();

    let model = model(
        21,
        graph(
            "test_GatherBlockQuantizedInt4_graph",
            vec![],
            vec![f32_output("Y", &[3, cols])],
            vec![gbq],
            vec![
                data,
                i64_init("indices", &[3], &[0, 5, 2]),
                f32_init("scales", &[rows, blocks], &scales),
            ],
        ),
    );
    with_ms_domain(model, 1)
}

/// MoE with fused interleaved SwiGLU (gpt-oss style): 4 experts, top-2
/// routing with normalized weights, alpha/limit clamps in play. Weight
/// layouts follow the ORT spec: fc1 [E, 2*inter, hidden], fc2 [E, hidden,
/// inter], both applied as x @ w^T.
fn build_moe() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    let (num_experts, hidden, inter, rows) = (4i64, 8i64, 4i64, 3i64);
    let fc1_out = 2 * inter;

    let det = |seed: i64, len: i64| -> Vec<f32> {
        (0..len)
            .map(|i| (((i * 37 + seed * 101) % 19) as f32 - 9.0) * 0.11)
            .collect()
    };

    let mut moe = node(
        "MoE",
        "test_moe",
        &["X", "router_logits", "fc1_w", "fc1_b", "fc2_w", "fc2_b"],
        &["Y"],
        &[
            attr_int("k", 2),
            attr_int("normalize_routing_weights", 1),
            attr_int("swiglu_fusion", 1),
            attr_int("use_sparse_mixer", 0),
            attr_string("activation_type", "swiglu"),
            attr_float("activation_alpha", 1.702),
            attr_float("activation_beta", 1.0),
            attr_float("swiglu_limit", 7.0),
        ],
    );
    moe.domain = "com.microsoft".to_string();

    let model = model(
        17,
        graph(
            "test_MoE_graph",
            vec![
                f32_input("X", &[rows, hidden]),
                f32_input("router_logits", &[rows, num_experts]),
            ],
            vec![f32_output("Y", &[rows, hidden])],
            vec![moe],
            vec![
                f32_init(
                    "fc1_w",
                    &[num_experts, fc1_out, hidden],
                    &det(1, num_experts * fc1_out * hidden),
                ),
                f32_init(
                    "fc1_b",
                    &[num_experts, fc1_out],
                    &det(2, num_experts * fc1_out),
                ),
                f32_init(
                    "fc2_w",
                    &[num_experts, hidden, inter],
                    &det(3, num_experts * hidden * inter),
                ),
                f32_init(
                    "fc2_b",
                    &[num_experts, hidden],
                    &det(4, num_experts * hidden),
                ),
            ],
        ),
    );
    with_ms_domain(model, 1)
}

#[test]
fn moe_swiglu_matches_ort() {
    assert_op_matches_ort(build_moe(), ExpectConvertOp::Success, 17);
}

/// QMoE (blockwise 4- or 8-bit) with the same routing/activation
/// configuration as build_moe. Validates the nibble order and
/// (q - zero_point) * scale dequantization against ORT's kernel.
fn build_qmoe(bits: i64) -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    let (num_experts, hidden, inter, rows, block_size) = (4i64, 32i64, 16i64, 3i64, 32i64);
    let fc1_out = 2 * inter;
    let per_byte = 8 / bits;

    let packed = |seed: i64, rows: i64, cols: i64| -> Vec<u8> {
        (0..rows * cols / per_byte)
            .map(|i| ((i * 7 + seed * 13) % 256) as u8)
            .collect()
    };
    // Normalize weight magnitudes across bit widths (|q - zp| <= 2^(bits-1))
    // so outputs stay small enough for the runner's absolute tolerance.
    let scale_norm = (1i64 << (bits - 1)) as f32 / 8.0;
    let scales = |seed: i64, rows: i64, blocks: i64| -> Vec<f32> {
        (0..rows * blocks)
            .map(|i| (0.01 + ((i * 11 + seed * 3) % 17) as f32 * 0.005) / scale_norm)
            .collect()
    };

    let fc1_blocks = hidden / block_size;
    let fc2_blocks = (inter + block_size - 1) / block_size;

    let mut qmoe = node(
        "QMoE",
        "test_qmoe",
        &[
            "X",
            "router_logits",
            "fc1_w",
            "fc1_scales",
            "fc1_b",
            "fc2_w",
            "fc2_scales",
            "fc2_b",
        ],
        &["Y"],
        &[
            attr_int("k", 2),
            attr_int("normalize_routing_weights", 1),
            attr_int("swiglu_fusion", 1),
            attr_int("use_sparse_mixer", 0),
            attr_int("expert_weight_bits", bits),
            attr_int("block_size", block_size),
            attr_string("activation_type", "swiglu"),
            attr_float("activation_alpha", 1.702),
            attr_float("activation_beta", 1.0),
            attr_float("swiglu_limit", 7.0),
        ],
    );
    qmoe.domain = "com.microsoft".to_string();

    let model = model(
        17,
        graph(
            "test_QMoE_graph",
            vec![
                f32_input("X", &[rows, hidden]),
                f32_input("router_logits", &[rows, num_experts]),
            ],
            vec![f32_output("Y", &[rows, hidden])],
            vec![qmoe],
            vec![
                u8_init(
                    "fc1_w",
                    &[num_experts, fc1_out, hidden / per_byte],
                    &packed(1, num_experts * fc1_out, hidden),
                ),
                f32_init(
                    "fc1_scales",
                    &[num_experts, fc1_out, fc1_blocks],
                    &scales(2, num_experts * fc1_out, fc1_blocks),
                ),
                f32_init(
                    "fc1_b",
                    &[num_experts, fc1_out],
                    &scales(3, num_experts, fc1_out),
                ),
                u8_init(
                    "fc2_w",
                    &[num_experts, hidden, inter / per_byte],
                    &packed(4, num_experts * hidden, inter),
                ),
                f32_init(
                    "fc2_scales",
                    &[num_experts, hidden, fc2_blocks],
                    &scales(5, num_experts * hidden, fc2_blocks),
                ),
                f32_init(
                    "fc2_b",
                    &[num_experts, hidden],
                    &scales(6, num_experts, hidden),
                ),
            ],
        ),
    );
    with_ms_domain(model, 1)
}

#[test]
fn qmoe_swiglu_4bit_matches_ort() {
    assert_op_matches_ort(build_qmoe(4), ExpectConvertOp::Success, 17);
}

#[test]
fn qmoe_swiglu_8bit_matches_ort() {
    assert_op_matches_ort(build_qmoe(8), ExpectConvertOp::Success, 17);
}

/// GatherBlockQuantized: 4- or 8-bit table with explicit packed zero points,
/// constant indices, gather_axis 0.
fn build_gather_block_quantized(bits: i64) -> ModelProto {
    build_gather_block_quantized_with(bits, &[3], &[0, 5, 2])
}

/// `indices_shape`/`indices` let the batched (rank-2) gather path be exercised.
fn build_gather_block_quantized_with(
    bits: i64,
    indices_shape: &[i64],
    indices: &[i64],
) -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    let (rows, cols, block_size) = (8i64, 32i64, 16i64);
    let per_byte = 8 / bits;
    let blocks = cols / block_size;

    let data: Vec<u8> = (0..rows * cols / per_byte)
        .map(|i| ((i * 5 + 3) % 256) as u8)
        .collect();
    let scales: Vec<f32> = (0..rows * blocks)
        .map(|i| 0.02 + (i % 7) as f32 * 0.01)
        .collect();
    let zp: Vec<u8> = (0..(rows * blocks / per_byte).max(1))
        .map(|i| ((i * 3 + 1) % 256) as u8)
        .collect();

    let mut gbq = node(
        "GatherBlockQuantized",
        "test_gbq",
        &["data", "indices", "scales", "zero_points"],
        &["Y"],
        &[
            attr_int("bits", bits),
            attr_int("block_size", block_size),
            attr_int("gather_axis", 0),
            attr_int("quantize_axis", 1),
        ],
    );
    gbq.domain = "com.microsoft".to_string();

    let model = model(
        21,
        graph(
            "test_GatherBlockQuantized_graph",
            vec![],
            vec![f32_output("Y", &[indices_shape, &[cols]].concat())],
            vec![gbq],
            vec![
                u8_init("data", &[rows, cols / per_byte], &data),
                i64_init("indices", indices_shape, indices),
                f32_init("scales", &[rows, blocks], &scales),
                u8_init("zero_points", &[rows, blocks / per_byte.min(blocks)], &zp),
            ],
        ),
    );
    with_ms_domain(model, 1)
}

#[test]
fn gather_block_quantized_4bit_matches_ort() {
    assert_op_matches_ort(
        build_gather_block_quantized(4),
        ExpectConvertOp::Success,
        21,
    );
}

#[test]
fn gather_block_quantized_batched_indices_matches_ort() {
    assert_op_matches_ort(
        build_gather_block_quantized_with(4, &[2, 2], &[7, 0, 3, 3]),
        ExpectConvertOp::Success,
        21,
    );
}

#[test]
fn gather_block_quantized_8bit_matches_ort() {
    assert_op_matches_ort(
        build_gather_block_quantized(8),
        ExpectConvertOp::Success,
        21,
    );
}

/// MatMulNBits with bits=8: one byte per value, default zero point 128.
fn build_matmul_nbits_8bit() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    let (k, n, block_size) = (32i64, 4i64, 32i64);
    let b_data: Vec<u8> = (0..n * k).map(|i| ((i * 11 + 7) % 256) as u8).collect();
    let scales: Vec<f32> = (0..n).map(|i| 0.05 + i as f32 * 0.01).collect();

    let mut nbits = node(
        "MatMulNBits",
        "test_matmul_nbits8",
        &["A", "B", "scales"],
        &["Y"],
        &[
            attr_int("K", k),
            attr_int("N", n),
            attr_int("bits", 8),
            attr_int("block_size", block_size),
        ],
    );
    nbits.domain = "com.microsoft".to_string();

    let model = model(
        17,
        graph(
            "test_MatMulNBits8_graph",
            vec![f32_input("A", &[2, k])],
            vec![f32_output("Y", &[2, n])],
            vec![nbits],
            vec![
                u8_init("B", &[n, 1, block_size], &b_data),
                f32_init("scales", &[n], &scales),
            ],
        ),
    );
    with_ms_domain(model, 1)
}

#[test]
fn matmul_nbits_8bit_matches_ort() {
    assert_op_matches_ort(build_matmul_nbits_8bit(), ExpectConvertOp::Success, 17);
}

/// SplitToSequence + SequenceAt with constant sizes/indices (the torch
/// `split()` export pattern) lower to slices; negative index exercised.
fn build_split_to_sequence() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    let split = node(
        "SplitToSequence",
        "test_sts",
        &["X", "sizes"],
        &["seq"],
        &[attr_int("axis", -2)],
    );
    let at0 = node("SequenceAt", "test_at0", &["seq", "idx0"], &["Y0"], &[]);
    let at1 = node("SequenceAt", "test_at1", &["seq", "idx_neg"], &["Y1"], &[]);

    model(
        17,
        graph(
            "test_SplitToSequence_graph",
            vec![f32_input("X", &[2, 7, 4])],
            vec![f32_output("Y0", &[2, 3, 4]), f32_output("Y1", &[2, 4, 4])],
            vec![split, at0, at1],
            vec![
                i64_init("sizes", &[2], &[3, 4]),
                i64_init("idx0", &[], &[0]),
                i64_init("idx_neg", &[], &[-1]),
            ],
        ),
    )
}

#[test]
fn split_to_sequence_matches_ort() {
    assert_op_matches_ort(build_split_to_sequence(), ExpectConvertOp::Success, 17);
}

/// Bidirectional LSTM with combined bias and initial states, requesting
/// Y, Y_h and Y_c (the pyannote pattern).
fn build_bidirectional_lstm() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    let (seq, batch, input, hidden) = (5i64, 1i64, 3i64, 4i64);
    let dirs = 2i64;
    let det = |seed: i64, len: i64| -> Vec<f32> {
        (0..len)
            .map(|i| (((i * 31 + seed * 17) % 23) as f32 - 11.0) * 0.05)
            .collect()
    };

    let lstm = node(
        "LSTM",
        "test_bilstm",
        &["X", "W", "R", "B", "", "initial_h", "initial_c"],
        &["Y", "Y_h", "Y_c"],
        &[
            attr_int("hidden_size", hidden),
            attr_string("direction", "bidirectional"),
        ],
    );

    model(
        17,
        graph(
            "test_BiLSTM_graph",
            vec![f32_input("X", &[seq, batch, input])],
            vec![
                f32_output("Y", &[seq, dirs, batch, hidden]),
                f32_output("Y_h", &[dirs, batch, hidden]),
                f32_output("Y_c", &[dirs, batch, hidden]),
            ],
            vec![lstm],
            vec![
                f32_init(
                    "W",
                    &[dirs, 4 * hidden, input],
                    &det(1, dirs * 4 * hidden * input),
                ),
                f32_init(
                    "R",
                    &[dirs, 4 * hidden, hidden],
                    &det(2, dirs * 4 * hidden * hidden),
                ),
                f32_init("B", &[dirs, 8 * hidden], &det(3, dirs * 8 * hidden)),
                f32_init(
                    "initial_h",
                    &[dirs, batch, hidden],
                    &det(4, dirs * batch * hidden),
                ),
                f32_init(
                    "initial_c",
                    &[dirs, batch, hidden],
                    &det(5, dirs * batch * hidden),
                ),
            ],
        ),
    )
}

#[test]
fn bidirectional_lstm_matches_ort() {
    assert_op_matches_ort(build_bidirectional_lstm(), ExpectConvertOp::Success, 17);
}

/// If with a shape-derived constant condition inlines the taken branch.
fn build_constant_if() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    let then_g = graph(
        "then_g",
        vec![],
        vec![f32_output("branch_out", &[2, 3])],
        vec![node(
            "Add",
            "then_add",
            &["x", "delta"],
            &["branch_out"],
            &[],
        )],
        vec![f32_init("delta", &[1], &[1.0])],
    );
    let else_g = graph(
        "else_g",
        vec![],
        vec![f32_output("branch_out", &[2, 3])],
        vec![node(
            "Sub",
            "else_sub",
            &["x", "delta"],
            &["branch_out"],
            &[],
        )],
        vec![f32_init("delta", &[1], &[2.0])],
    );

    let mut if_node = node("If", "test_if", &["cond"], &["y"], &[]);
    if_node
        .attribute
        .push(onnx2webnn::protos::onnx::AttributeProto {
            name: "then_branch".to_string(),
            r#type: 5, // GRAPH
            g: Some(then_g),
            ..Default::default()
        });
    if_node
        .attribute
        .push(onnx2webnn::protos::onnx::AttributeProto {
            name: "else_branch".to_string(),
            r#type: 5, // GRAPH
            g: Some(else_g),
            ..Default::default()
        });

    let nodes = vec![
        node("Shape", "shape", &["x"], &["xs"], &[]),
        node(
            "Gather",
            "gather",
            &["xs", "idx"],
            &["d0"],
            &[attr_int("axis", 0)],
        ),
        node("Equal", "eq", &["d0", "two"], &["cond_u8"], &[]),
        node(
            "Cast",
            "cast",
            &["cond_u8"],
            &["cond"],
            &[attr_int("to", 9)],
        ),
        if_node,
    ];
    model(
        17,
        graph(
            "test_ConstIf_graph",
            vec![f32_input("x", &[2, 3])],
            vec![f32_output("y", &[2, 3])],
            nodes,
            vec![i64_init("idx", &[], &[0]), i64_init("two", &[], &[2])],
        ),
    )
}

#[test]
fn constant_if_inlines_and_matches_ort() {
    assert_op_matches_ort(build_constant_if(), ExpectConvertOp::Success, 17);
}

#[test]
fn group_query_attention_matches_ort() {
    assert_op_matches_ort(build_gqa(), ExpectConvertOp::Success, 17);
}

#[test]
fn group_query_attention_packed_qkv_matches_ort() {
    assert_op_matches_ort(build_gqa_with(true, None), ExpectConvertOp::Success, 17);
}

#[test]
fn group_query_attention_rotary_matches_ort() {
    assert_op_matches_ort(
        build_gqa_with(false, Some(false)),
        ExpectConvertOp::Success,
        17,
    );
}

#[test]
fn group_query_attention_rotary_interleaved_packed_matches_ort() {
    assert_op_matches_ort(
        build_gqa_with(true, Some(true)),
        ExpectConvertOp::Success,
        17,
    );
}

#[test]
fn gather_block_quantized_int4_matches_ort() {
    assert_op_matches_ort(
        build_gather_block_quantized_int4(),
        ExpectConvertOp::Success,
        21,
    );
}

#[test]
fn matmul_bnb4_nf4_matches_ort() {
    assert_op_matches_ort(build_matmul_bnb4(1), ExpectConvertOp::Success, 17);
}

#[test]
fn matmul_bnb4_fp4_matches_ort() {
    assert_op_matches_ort(build_matmul_bnb4(0), ExpectConvertOp::Success, 17);
}
