/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
//! ONNX `QLinearMatMul` operator conversion tests (fixture opsets: 10, 21).
// Auto-generated by scripts/generate_rust_op_conversion_tests.py — do not edit.

use crate::common::{assert_op_matches_ort, ExpectConvertOp};
use onnx2webnn::protos::onnx::ModelProto;

fn build_fixture_opset_10() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        10,
        graph(
            "test_QLinearMatMul_graph",
            vec![],
            vec![u8_output("y", &[1, 1])],
            vec![node(
                "QLinearMatMul",
                "test",
                &[
                    "a",
                    "a_scale",
                    "a_zero_point",
                    "b",
                    "b_scale",
                    "b_zero_point",
                    "y_scale",
                    "y_zero_point",
                ],
                &["y"],
                &[],
            )],
            vec![
                u8_init("a", &[1, 2], &[1, 2]),
                f32_init("a_scale", &[], &[0.5]),
                u8_init("a_zero_point", &[], &[0]),
                u8_init("b", &[2, 1], &[3, 4]),
                f32_init("b_scale", &[], &[0.25]),
                u8_init("b_zero_point", &[], &[0]),
                f32_init("y_scale", &[], &[0.125]),
                u8_init("y_zero_point", &[], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_10() {
    assert_op_matches_ort(build_fixture_opset_10(), ExpectConvertOp::UnsupportedOp, 10);
}

fn build_fixture_opset_21() -> ModelProto {
    use onnx2webnn::test_models::prelude::*;

    model(
        21,
        graph(
            "test_QLinearMatMul_graph",
            vec![],
            vec![u8_output("y", &[1, 1])],
            vec![node(
                "QLinearMatMul",
                "test",
                &[
                    "a",
                    "a_scale",
                    "a_zero_point",
                    "b",
                    "b_scale",
                    "b_zero_point",
                    "y_scale",
                    "y_zero_point",
                ],
                &["y"],
                &[],
            )],
            vec![
                u8_init("a", &[1, 2], &[1, 2]),
                f32_init("a_scale", &[], &[0.5]),
                u8_init("a_zero_point", &[], &[0]),
                u8_init("b", &[2, 1], &[3, 4]),
                f32_init("b_scale", &[], &[0.25]),
                u8_init("b_zero_point", &[], &[0]),
                f32_init("y_scale", &[], &[0.125]),
                u8_init("y_zero_point", &[], &[0]),
            ],
        ),
    )
}

#[test]
fn convert_op_opset_21() {
    assert_op_matches_ort(build_fixture_opset_21(), ExpectConvertOp::UnsupportedOp, 21);
}
